apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-github-worker
  labels: &ref_0
    app.kubernetes.io/name: taskcluster-github
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-github-worker
    app.kubernetes.io/part-of: taskcluster
spec:
  replicas: {{ int (.Values.github.procs.worker.replicas) }}
  selector:
    matchLabels: *ref_0
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-github-secret.yaml") . | sha256sum }}'
      labels: *ref_0
    spec:
      serviceAccountName: taskcluster-github
      containers:
        - name: taskcluster-github
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - github/worker
          resources:
            requests:
              cpu: '{{ .Values.github.procs.worker.cpu }}'
              memory: '{{ .Values.github.procs.worker.memory }}'
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: taskcluster-github
          ports: []
