apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-notify-irc
  labels: &ref_0
    app.kubernetes.io/name: taskcluster-notify
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-notify-irc
    app.kubernetes.io/part-of: taskcluster
spec:
  replicas: {{ int (.Values.notify.procs.irc.replicas) }}
  selector:
    matchLabels: *ref_0
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-notify-secret.yaml") . | sha256sum }}'
      labels: *ref_0
    spec:
      serviceAccountName: taskcluster-notify
      containers:
        - name: taskcluster-notify
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - notify/irc
          resources:
            requests:
              cpu: '{{ .Values.notify.procs.irc.cpu }}'
              memory: '{{ .Values.notify.procs.irc.memory }}'
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: taskcluster-notify
          ports: []
